# Serge Voilokov, 2015.
# Generate C version files.
# Version string is generated by "git describe --tags --long"
# Example: cmake.1.0-10-g55205ee
# Where:
#     cmake.1.0 -- last tag on current brach
#     10        -- number of commits since last tag
#     g55205ee  -- g character and short commit hash

OUTDIR=$1

(
	echo 'extern const char app_version[];'
	echo 'extern const char app_date[];'
	echo 'extern const char app_diff_stat[];'
	echo 'extern const char app_diff_full[];'
) > $OUTDIR/version.h

(
	echo 'const char app_version[] = "'`git describe --tags --long`'";'
	echo 'const char app_date[] = "'`git log -n 1 --format=%ai`'";'

	echo 'const char app_diff_stat[] = ""'
	git diff --stat |sed 's/^/\"/; s/$/\\n"/'
	echo '"";'

	echo 'const char app_diff_full[] = ""'
	git diff -U0 |sed 's/\\/\\\\/g; s/\\n/\\\\n/g; s/\"/\\"/g; s/^/\"/; s/$/\\n"/'
	echo '"";'
) > $OUTDIR/version.c
