/*
 * Serge Voilokov, 2015.
 * Generate C version files.
 * Version string is generated by "git describe --tags --long"
 * Example: cmake.1.0-10-g55205ee
 * Where:
 *     cmake.1.0 -- last tag on current brach
 *     10        -- number of commits since last tag
 *     g55205ee  -- g character and short commit hash
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <err.h>


static void
exec_cmd(const char *cmd, FILE *fout)
{
	char s[500];

	FILE *pcmd = popen(cmd, "r");
	if (pcmd == NULL)
		err(1, "cannot start git describe");
	fgets(s, 500, pcmd);
	if (s[strlen(s)-1] == '\n')
		s[strlen(s)-1] = 0;
	fputs(s, fout);
	int rc = pclose(pcmd);
	if (rc != 0)
		errc(1, rc, "cannot execute: %s", cmd);
}

int main(int argc, char **argv)
{
	FILE *fh, *fc;
	char *hfile, *cfile;
	const char *outdir;

	if (argc < 2) {
		printf("usage: mkversion OUTDIR\n");
		exit(1);
	}

	outdir = argv[1];

	asprintf(&hfile, "%s/version.h", outdir);
	asprintf(&cfile, "%s/version.c", outdir);

	fh = fopen(hfile, "wt");
	if (fh == NULL)
		err(1, "cannot open %s", hfile);

	fc = fopen(cfile, "wt");
	if (fc == NULL)
		err(1, "cannot open %s", cfile);

	fprintf(fh,
		"extern const char app_version[];\n"
		"extern const char app_date[];\n"
		"extern const char app_diff_stat[];\n"
		"extern const char app_diff_full[];\n");

	fclose(fh);

	fprintf(fc, "const char app_version[] = \"");
	exec_cmd("git describe --tags --long", fc);
	fprintf(fc, "\";\n");

	fprintf(fc, "const char app_date[] = \"");
	exec_cmd("git log -n 1 --format=%ai", fc);
	fprintf(fc, "\";\n");

	fclose(fh);
	fclose(fc);
	free(hfile);
	free(cfile);
}















