/*
 * Serge Voilokov, 2015.
 * Generate C version files.
 * Version string is generated by "git describe --tags --long"
 * Example: cmake.1.0-10-g55205ee
 * Where:
 *     cmake.1.0 -- last tag on current brach
 *     10        -- number of commits since last tag
 *     g55205ee  -- g character and short commit hash
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <err.h>


static int
exec_cmd(const char *cmd, FILE *fout)
{
	char s[500];

	FILE *pcmd = popen(cmd, "r");
	if (pcmd == NULL)
		err(1, "cannot start git describe");
	fgets(s, 500, pcmd);
	if (s[strlen(s)-1] == '\n')
		s[strlen(s)-1] = 0;
	fputs(s, fout);
	int rc = pclose(pcmd);
	if (rc != 0)
		warnc(rc, "cannot execute: %s", cmd);
	return rc;
}

int main(int argc, char **argv)
{
	FILE *fh = NULL, *fc = NULL;
	char *hfile, *cfile;
	const char *outdir;
	int ret = 1;

	if (argc < 2) {
		printf("usage: mkversion OUTDIR\n");
		exit(1);
	}

	outdir = argv[1];

	asprintf(&hfile, "%s/version.h", outdir);
	asprintf(&cfile, "%s/version.c", outdir);

	fh = fopen(hfile, "wt");
	if (fh == NULL) {
		warn("cannot open %s", hfile);
		goto out;
	}

	fc = fopen(cfile, "wt");
	if (fc == NULL) {
		warn("cannot open %s", cfile);
		goto out;
	}

	fprintf(fh,
		"extern const char app_version[];\n"
		"extern const char app_date[];\n");

	fprintf(fc, "const char app_version[] = \"");
	if (exec_cmd("git describe --tags --long", fc) != 0)
		goto out;
	fprintf(fc, "\";\n");

	fprintf(fc, "const char app_date[] = \"");
	if (exec_cmd("git log -n 1 --format=%ai", fc) != 0)
		goto out;
	fprintf(fc, "\";\n");

	ret = 0;
out:
	if (fh != NULL)
		fclose(fh);

	if (fc != NULL)
		fclose(fc);

	free(hfile);
	free(cfile);

	return ret;
}















